/* ============================================================
   DATABANKA PANTOMIMY
   Samostatný .js soubor (ne JSON): načítá se přes <script src>,
   takže funguje i přes file:// bez lokálního serveru a bez fetch.
   Formát: PANTOMIMA_DB[jazyk][kategorie][obtížnost] = pole slov.
   Obtížnost: 1 = lehká, 2 = střední, 3 = těžká.
   Prvek pole je buď jen řetězec ("Slon"), nebo dvojice
   [slovo, nápověda] (["Slon","Napodob chobot mávající před obličejem"]).
   Nápověda je nepovinná — u řetězce se prostě nezobrazí.
   Přidání slova = připsat řetězec (nebo dvojici) do příslušného pole.
   ============================================================ */
const PANTOMIMA_DB = {
cs: {
"Zvířata": {
 1: [
  ["Slon","Napodob chobot mávající před obličejem"],
  ["Žirafa","Nataž krk a okusuj vysoko ze stromu"],
  ["Kočka","Olízni si tlapku a umývej si jí obličej"],
  ["Pes","Vrť ocasem a čenichej kolem"],
  ["Had","Plaz se po břiše a syč jazykem"],
  ["Opice","Škrábej se pod paží a skákej jako po stromech"],
  ["Kráva","Přežvykuj a předveď dojení vemene"],
  ["Kůň","Cválej a hrabej kopytem o zem"],
  ["Králík","Skákej po dvou a mrskej ušima"],
  ["Ryba","Otevírej ústa naprázdno a mávej rukama jako ploutvemi"],
  ["Pták","Mávej rukama jako křídly a předveď let"],
  ["Žába","Skákej v podřepu a vypoulej oči"],
  ["Motýl","Mávej rukama pomalu jako křídly a poletuj"],
  ["Včela","Bzuč a předveď žihadlo zadečkem"],
  ["Lev","Zařvi a předveď hřívu kolem obličeje"],
  ["Tygr","Plížuj se a naznač pruhy drápy"],
  ["Medvěd","Kolébej se a předveď velké tlapy s drápy"],
  ["Myš","Dělej drobné krůčky a čenichej po kousku sýra"],
  ["Slepice","Kdákej a klepej hlavou při hrabání"],
  ["Kohout","Zakokrhej a napřimuj hrudník"],
  ["Prase","Chrochtej a čum rypákem po zemi"],
  ["Ovce","Bečí a předveď vlnu na těle"],
  ["Kachna","Kejhej a kolébej se v chůzi"],
  ["Netopýr","Viset hlavou dolů a mávej křídly"],
  ["Klokan","Skákej po dvou nohou s rukama u hrudi"],
  ["Tučňák","Kolébej se s rukama u těla a špičkami ven"],
  ["Pavouk","Předveď osm nohou lezoucích po zemi"],
  ["Želva","Pomalu se plaz a schovej hlavu do krunýře"],
  ["Krokodýl","Otevírej tlamu a plaz se po zemi"],
  ["Sova","Otáčej hlavou dokola a předveď velké oči"],
  ["Hroch","Otevři obrovskou tlamu a těžkopádně se pohybuj"],
  ["Nosorožec","Naznač roh na nose a dupej vpřed"],
  ["Zebra","Předveď pruhy po těle a pádi jako kůň"],
  ["Labuť","Elegantně natáhni krk a plav rukama"],
  ["Holub","Poskakuj s hlavou pokyvující dopředu"],
  ["Vrána","Krákej a poskakuj s rukama za zády"],
  ["Beruška","Předveď puntíky na zádech a poletuj"],
  ["Žížala","Plaz se po zemi bez nohou"],
  ["Housenka","Vlň se po zemi po délce těla"],
  ["Kapr","Otevírej ústa jako ryba a plav u dna"],
  ["Husa","Sykej s nataženým krkem a mávej křídly nahoru"],
  ["Jehně","Skákej neohrabaně na tenkých nohách a mečet"],
  ["Kotě","Hraj si s klubíčkem a mňoukej potichu"],
  ["Štěně","Honič si ocas a radostně poskakuj"],
  ["Sele","Chrochtej pisklavě a rypákem hrabej v blátě"],
  ["Kuře","Pípej a klátivě se batol po zemi"],
  ["Vlaštovka","Předveď rychlý let nízko nad zemí"],
  ["Racek","Krouž s roztaženými křídly nad vodou a křič"],
  ["Slimák","Plaz se pomalu bez ulity a nechávej stopu"],
  ["Šnek","Vylez z ulity a plaz se pomaličku"],
  ["Klíště","Zaboř se drobným pohybem do kůže a drž se pevně"],
  ["Sysel","Postav se na zadní a rozhlížej se po okolí"]
 ],
 2: [
  ["Veverka","Skákej po stromech a hlodej oříšek v tlapkách"],
  ["Ježek","Schoulíš se do klubíčka s naježenými bodlinami"],
  ["Datel","Ťukej hlavou rychle o strom"],
  ["Čáp","Stůj na jedné noze a klapej dlouhým zobákem"],
  ["Plameňák","Stůj na jedné noze a předveď dlouhý zahnutý krk"],
  ["Chobotnice","Mávej osmi rukama jako chapadly kolem těla"],
  ["Žralok","Ploutví rukou nad hlavou a předveď ostré zuby"],
  ["Delfín","Skákej obloukem nad hladinou a vydávej pískání"],
  ["Velbloud","Kolíbej se s hrbem na zádech přes poušť"],
  ["Gorila","Bušíš se pěstmi do hrudi a kolíbej se do stran"],
  ["Lenochod","Pohybuj se extrémně pomalu a viset na větvi"],
  ["Mravenec","Nes něco mnohonásobně těžšího než ty sám"],
  ["Komár","Bzuč vysokým tónem u ucha a píchni"],
  ["Moucha","Poletuj nervózně a mni si nožičky"],
  ["Hlemýžď","Plaz se s ulitou na zádech a vystrč tykadla"],
  ["Krtek","Hrab si tunel rukama pod zemí a mhouř oči"],
  ["Liška","Plíž se potichu a mrskej huňatým ocasem"],
  ["Vlk","Zavyj s hlavou zvednutou k měsíci"],
  ["Jelen","Předveď parohy rukama nad hlavou a vzpřimuj se"],
  ["Orel","Roztáhni ruce jako křídla a vznášej se vysoko"],
  ["Papoušek","Opakuj po někom slova a předveď pestré peří"],
  ["Páv","Rozevři ocas do vějíře a hrdě se procházej"],
  ["Osel","Zabraň se na místě a zahýkej"],
  ["Koza","Bodej hlavou a žvýkej cokoliv okolo"],
  ["Bobr","Ohlodávej dřevo a plácni ocasem o vodu"],
  ["Vydra","Kloužej se po břiše a hraj si ve vodě"],
  ["Mrož","Předveď velké kly a plácej se na ledové kře"],
  ["Tuleň","Plácej ploutvemi a vydávej štěkavé zvuky"],
  ["Rak","Předveď klepeta a couvej pozpátku"],
  ["Ještěrka","Rychle přebíhej po zemi a strň nehybně"],
  ["Gepard","Sprintuj v podřepu co nejrychleji"],
  ["Rys","Plíž se potichu s pomrkávajícíma ušima"],
  ["Los","Nes obrovské parohy a kráčej těžkopádně"],
  ["Sob","Táhni saně a předveď rozvětvené parohy"],
  ["Lama","Vypni krk a naznač plivnutí"],
  ["Pštros","Utíkej rychle s dlouhýma nohama a strč hlavu do písku"],
  ["Úhoř","Vlň se hadovitě jako ve vodě"],
  ["Vážka","Poletuj rychle s průhlednými křídly na místě"],
  ["Cvrček","Vydávej cvrkání třením nohou"],
  ["Kobylka","Skákej vysoko na zadních nohách"],
  ["Štír","Zvedni ocas nad hlavu a předveď žihadlo"],
  ["Krocan","Nafoukni hruď a předveď lalok pod zobákem"],
  ["Antilopa","Vyskakuj vysoko do stran na útěku před predátorem"],
  ["Puma","Plíž se tiše a vyskoč vysoko na kořist"],
  ["Šakal","Kluš vytrvale ve smečce a vyj potichu"],
  ["Kajman","Číhej těsně pod hladinou s vyčnívajícíma očima"],
  ["Ondatra","Plav na hladině a stav si hnízdo z rákosí"],
  ["Kormorán","Suš roztažená křídla na kameni po potopení"],
  ["Jestřáb","Střemhlav se vrhni na kořist z výšky"],
  ["Sokol","Předveď střemhlavý let extrémní rychlostí"],
  ["Skunk","Zvedni ocas a předveď smradlavý sprej"],
  ["Dikobraz","Najež ostny po celém těle při ohrožení"],
  ["Mýval","Umývej si potravu ve vodě obratnýma tlapkama"],
  ["Vombat","Hrab nízkou noru a kutálej se jako kostka"],
  ["Fretka","Protahuj se dlouhým tělem úzkou skulinou"],
  ["Norek","Plav mrštně a lov ve vodě i na souši"]
 ],
 3: [
  ["Chameleon","Pomalu měň barvu a otáčej očima do dvou směrů"],
  ["Medúza","Vlň se pomalu v beztížném stavu s dlouhými chapadly"],
  ["Mlok","Plaz se pomalu s pestrobarevnou kůží u vody"],
  ["Svišť","Pískni varovně a postav se na zadní"],
  ["Pásovec","Srolej se do pevné kuličky s pancířem"],
  ["Mravenečník","Vyplázni dlouhý jazyk hluboko do mraveniště"],
  ["Ptakopysk","Předveď zobákovitý čenich a plovací blány"],
  ["Škeble","Zaklapni pevně dvě poloviny lastury"],
  ["Světluška","Blikej zadečkem v tmě jako maják"],
  ["Kudlanka","Drž přední nohy sepnuté jako v modlitbě a znehybni"],
  ["Rejnok","Vlň se plochým tělem těsně nad dnem"],
  ["Mořský koník","Plav svisle a stočený ocas obtoč kolem řasy"],
  ["Jezevec","Hrab noru a předveď pruhovanou masku na hlavě"],
  ["Rosomák","Buď zavalitý a nekompromisně braň svou kořist"],
  ["Surikata","Postav se zpříma na zadní a hlídkuj v houfu"],
  ["Emu","Utíkej rychle na dlouhých nohách s krátkými křídly"],
  ["Axolotl","Plav s třásnitými žábrami po stranách hlavy"],
  ["Tapír","Předveď krátký chobotovitý čenich a rypej v bahně"],
  ["Kapybara","Poleháváš líně u vody jako obří morče"],
  ["Lemur","Skákej mezi větvemi s ocasem pruhovaným jako mýval"],
  ["Kolibřík","Zůstaň na místě rychlým vrtěním rukou-křídel u květu"],
  ["Albatros","Roztáhni obrovská křídla a plachti bez mávání"],
  ["Piraňa","Cvakej ostrými zoubky naprázdno"],
  ["Leguán","Nehybně se sluň a předveď hřeben na zádech"],
  ["Hyena","Vydávej chraplavý smích a poškubávej hlavou"],
  ["Sépie","Vystřel inkoust a měň barvu kůže jako maskování"],
  ["Kalan","Plav na zádech a rozbíjej mušli kamenem na hrudi"],
  ["Fenek","Předveď obří uši a poskakuj po písku pouště"],
  ["Okapi","Předveď pruhované nohy jako zebra a dlouhý žirafí krk"],
  ["Narval","Vystrč dlouhý spirálovitý kel z hlavy"],
  ["Dronte","Batol se neohrabaně a mávej zakrslými křídly bez letu"],
  ["Outloň","Pohybuj se extrémně pomalu s obříma kulatýma očima"],
  ["Numbat","Vyhrabávej termity dlouhým lepkavým jazykem"],
  ["Manul","Přikrč se do placata a zaraž se s naježenou srstí"]
 ]
},
"Povolání": {
 1: [
  ["Kuchař","Míchej v hrnci a ochutnávej z vařečky"],
  ["Hasič","Namiř hadici a stříkej na pomyslný oheň"],
  ["Policista","Zastav dopravu zvednutou dlaní a piskej do píšťalky"],
  ["Lékař","Poslouchej srdce fonendoskopem a piš recept"],
  ["Učitel","Ukazuj na tabuli a přísně hrozíš ukazovákem"],
  ["Zubař","Nahlédni do otevřených úst s malým zrcátkem"],
  ["Kadeřník","Stříhej nůžkami ve vzduchu kolem hlavy"],
  ["Malíř","Táhni válečkem se štětcem po zdi nahoru dolů"],
  ["Zpěvák","Drž pomyslný mikrofon a zpívej s gestem do publika"],
  ["Řidič","Drž volant a řaď rychlosti"],
  ["Fotograf","Přilož foťák k oku a mačkej spoušť"],
  ["Zahradník","Kopej motyčkou a zalévej konví záhon"],
  ["Rybář","Hoď udici a navíjej naviják"],
  ["Pekař","Hněť těsto a vytahuj plech z pece"],
  ["Číšník","Nes tác vysoko nad hlavou mezi stoly"],
  ["Uklízečka","Otírej hadrem plochy a vytírej podlahu mopem"],
  ["Zedník","Nanášej maltu zednickou lžící na cihly"],
  ["Pošťák","Rozvážej dopisy na kole a vhazuj je do schránek"],
  ["Prodavač","Váž zboží na váze a podávej přes pult"],
  ["Farmář","Krm slepice a doj krávu na dvoře"],
  ["Voják","Pochoduj vzpřímeně a salutuj"],
  ["Zdravotní sestra","Měř tlak a piš injekci"],
  ["Automechanik","Lež pod autem a utahuj klíčem šroub"],
  ["Taxikář","Zastav u chodníku a otevři dveře pro pasažéra"],
  ["Herec","Přehnaně gestikuluj a klaněj se publiku"],
  ["Tanečnice","Točí se na špičkách s pažemi nad hlavou"],
  ["Zmrzlinář","Naber kopeček zmrzliny lžící do kornoutu"],
  ["Barista","Šlehej mléko napěňovačem a kresli srdíčko do kávy"],
  ["Cukrář","Zdob dort stříkacím sáčkem s polevou"],
  ["Sklenář","Řež sklo diamantovým nožem a vsazuj tabuli do rámu"],
  ["Knihovník","Přikládej prst na ústa a razítkuj knihu"],
  ["Vrátný","Otevírej dveře a kontroluj příchozí u vstupu"],
  ["Myč aut","Drhni kartáčem karoserii a stříkej vodu hadicí"],
  ["Ochranka","Zkřiž ruce na hrudi a rozhlížej se přísně kolem"],
  ["Chůva","Kolébej miminko v náručí a krm ho lžičkou"],
  ["Krejčí","Měř metrem postavu a špendli látku"]
 ],
 2: [
  ["Pilot","Ovládej řídicí páku a nakláněj se do zatáčky"],
  ["Kominík","Šplhej po komíně a čisti ho dlouhým kartáčem"],
  ["Chirurg","Nasaď si roušku a předstírej opatrný řez skalpelem"],
  ["Dirigent","Máchej taktovkou před neviditelným orchestrem"],
  ["Soudce","Buš kladívkem o stůl a vyhlas rozsudek"],
  ["Kněz","Žehnej rukama nad hlavami a předveď mši"],
  ["Veterinář","Prohlížej pomyslné zvíře na stole a hlaď ho"],
  ["Elektrikář","Šroubuj v rozvodné skříňce a testuj zkoušečkou"],
  ["Instalatér","Utahuj klíčem trubku pod dřezem"],
  ["Truhlář","Hobluj dřevo a zatloukej hřebíky do desky"],
  ["Švadlena","Šij na stroji a zapichuj špendlíky do látky"],
  ["Řezník","Sekej sekáčkem maso na pařezu"],
  ["Barman","Protřepej koktejl v shakeru a nalévej do sklenice"],
  ["Horník","Kopej krumpáčem hluboko pod zemí s lucernou na čele"],
  ["Dřevorubec","Kácej sekerou strom a utírej si pot"],
  ["Popelář","Zvedni popelnici a vysyp ji do vozu"],
  ["Astronaut","Pohybuj se v beztíži pomalými odrazy"],
  ["Potápěč","Plav s ploutvemi a dýchej z bomby"],
  ["Krotitel lvů","Máchej bičem a strkej hlavu do tlamy"],
  ["Žokej","Skloň se nízko nad koněm a pobízej ho bičíkem"],
  ["Moderátor","Drž kartičky a usmívej se do kamery"],
  ["Sochař","Otesávej kámen dlátem a kladívkem"],
  ["Masér","Hněť ramena a záda pomyslného pacienta"],
  ["Optik","Zkoušej brýle a měř zrak na tabuli"],
  ["Průvodčí","Prostříhávej jízdenky kleštěmi"],
  ["Hlídač","Obcházej s baterkou a kontroluj zamčené dveře"],
  ["Kaskadér","Padej dramaticky ze schodů a hned vstávej"],
  ["Klaun","Nasaď červený nos a přehnaně upadni"],
  ["Kouzelník","Vytáhni z klobouku králíka mávnutím hůlky"],
  ["Plavčík","Sleduj bazén a skoč po hlavě zachránit tonoucího"],
  ["Rozhodčí","Zapískej a zvedni žlutou kartu"],
  ["Trenér","Křič pokyny z lavičky a tleskej"],
  ["Recepční","Podávej klíč od pokoje přes pult s úsměvem"],
  ["Letuška","Ukazuj bezpečnostní pokyny rukama u uličky"],
  ["Strojvedoucí","Tahej za páku a troubi houkačkou"],
  ["Jeřábník","Ovládej páky a zvedej těžké břemeno vysoko"],
  ["Bagrista","Ovládej lžíci bagru a nabírej hlínu"],
  ["Pokrývač","Přibíjej tašky na střechu ve výškách"],
  ["Hodinář","Nasaď si lupu na oko a šroubuj drobná kolečka"],
  ["Zámečník","Vrtej se paklíčem v zámku a otevři dveře"],
  ["Ošetřovatel v zoo","Krm zvíře přes mříže a uklízej výběh"],
  ["Turistický průvodce","Ukazuj deštníkem na pamětihodnost a vyprávěj skupině"],
  ["Kovář","Buš kladivem do rozžhavené podkovy na kovadlině"],
  ["Modelka","Vykračuj si po molu s hrdým výrazem"],
  ["Zvonař","Odlévej zvon a poslouchej jeho tón úderem"],
  ["Cirkusový akrobat","Udělej salto a ukloň se s rozpaženýma rukama"],
  ["Provazochodec","Balancuj s tyčí na nataženém laně vysoko"],
  ["Cvičitel psů","Dávej povel dlaní a odměňuj pamlskem"],
  ["Lodní kapitán","Drž kormidlo a hleď dalekohledem na obzor"],
  ["Sokolník","Nastav koženou rukavici a vypusť dravce do vzduchu"],
  ["Domovník","Zameť dvůr a kontroluj vchod do domu"],
  ["Skladník","Skládej bedny na vysoký regál vysokozdvižným vozíkem"],
  ["Vinař","Šlapej hrozny bosýma nohama v kádi"],
  ["Pivovarník","Míchej slad v obrovském kotli a ochutnávej"],
  ["Mlynář","Sypej obilí do mlýnského kola nad mlecí kámen"],
  ["Tesař","Přitloukej trámy a měř úhel pravítkem"],
  ["Kamnář","Skládej cihly do kachlových kamen a hlaď omítku"],
  ["Košíkář","Splétej proutí do kulatého tvaru koše"],
  ["Zahradní architekt","Rozvrhuj rukama záhony a stříhej živý plot do tvaru"],
  ["Zvěrolékařská sestra","Přidržuj neklidné zvíře, zatímco ho ošetřuješ"]
 ],
 3: [
  ["Archeolog","Vykopávej opatrně štětečkem v písku"],
  ["Účetní","Ťukej rychle do kalkulačky a mračí se na čísla"],
  ["Programátor","Ťukej horečně do klávesnice a zírej do obrazovky"],
  ["Právník","Listuj v tlusté knize zákonů a gestikuluj v obhajobě"],
  ["Psycholog","Přikyvuj pomalu a piš si poznámky do notesu"],
  ["Meteorolog","Ukazuj na mapu s mraky a předpovídej počasí"],
  ["Včelař","Nasaď si síťovaný klobouk a vykuřuj úl"],
  ["Restaurátor","Jemně odstraňuj štětečkem prach ze starého obrazu"],
  ["Notář","Přikládej razítko a podepisuj listinu vážným výrazem"],
  ["Tlumočník","Poslouchej se sluchátky a rychle šeptej překlad"],
  ["Lékárník","Odvažuj prášky a podávej krabičku přes pult"],
  ["Geolog","Sbírej kamínky kladívkem a prohlížej je lupou"],
  ["Architekt","Rýsuj rovnítkem plány budovy na velký papír"],
  ["Novinář","Drž diktafon a horlivě si zapisuj odpovědi"],
  ["Špion","Plíž se kradmo a fotografuj skrytou kamerkou"],
  ["Detektiv","Prohlížej lupou stopy a zamyšleně si mni bradu"],
  ["Hrobník","Kopej lopatou hlubokou jámu"],
  ["Porodní asistentka","Uklidňuj rodičku a pomáhej jí dýchat"],
  ["Krupiér","Rozdávej karty a hrábni žetony přes stůl"],
  ["Sommeliér","Přičichni k vínu, zakruž sklenkou a ochutnej"],
  ["Exekutor","Klepej razantně na dveře a sepisuj majetek"],
  ["Kartářka","Rozprostři karty na stůl a tajemně věšti"],
  ["Šaman","Tancuj kolem ohně a chřestí rachotičkou"],
  ["Alchymista","Míchej lektvar v baňce nad plamenem"],
  ["Kartograf","Rýsuj obrysy pobřeží brkem na starou mapu"],
  ["Astronom","Dívej se dalekohledem vzhůru a zapisuj souřadnice hvězd"],
  ["Chemik","Kápni pipetou do zkumavky a sleduj bublání"],
  ["Loutkář","Tahej za neviditelné nitky nad loutkou"],
  ["Varhaník","Mačkej klávesy a šlapej pedály varhan oběma nohama"],
  ["Pyrotechnik","Opatrně přestřihávej drátek u nálože"],
  ["Ladič klavírů","Poklepávej ladičkou a napínej klíčem struny"],
  ["Diplomat","Potřásej si formálně rukou a nasaď zdvořilý úsměv"],
  ["Genetik","Prohlížej dvojšroubovici pod mikroskopem"],
  ["Paleontolog","Vykopávej opatrně dinosauří kost štětcem"],
  ["Filozof","Seď zamyšleně s bradou v dlani a přemýšlej nahlas"],
  ["Numismatik","Prohlížej starou minci lupou a leštíš ji"],
  ["Egyptolog","Odkrývej opatrně sarkofág v pyramidě"],
  ["Klenotník","Prohlížej diamant přes juvelírskou lupu v oku"],
  ["Vulkanolog","Odebírej vzorek lávy dlouhou tyčí u sopky"],
  ["Entomolog","Chytej hmyz síťkou a připichuj ho na destičku"],
  ["Ornitolog","Pozoruj ptáky dalekohledem a zapisuj si druhy"]
 ]
},
"Činnosti": {
 1: [
  ["Spaní","Slož ruce pod hlavu a naznač hluboké oddechování"],
  ["Běhání","Pumpuj lokty a vysoko zvedej kolena"],
  ["Jídlo","Nabírej neviditelnou vidličkou a žvýkej"],
  ["Pití","Zakloň hlavu a polykej ze sklenice"],
  ["Čtení","Otáčej stránky a sleduj řádky očima"],
  ["Psaní","Piš tužkou a klepej si o bradu při přemýšlení"],
  ["Mytí rukou","Pěň si dlaně mýdlem a oplachuj je"],
  ["Čištění zubů","Kmitej rukou u úst a vyplivni pastu"],
  ["Česání","Přejížděj hřebenem přes vlasy dokola"],
  ["Telefonování","Přilož ruku k uchu a gestikuluj při hovoru"],
  ["Řízení auta","Drž volant a řaď rychlostní páku"],
  ["Tancování","Vlň se do rytmu s výraznými kroky"],
  ["Zpívání","Otevírej ústa dokořán s rukou na hrudi"],
  ["Vaření","Míchej v hrnci a ochutnávej z vařečky"],
  ["Žehlení","Přejížděj žehličkou tam a zpět po prkně"],
  ["Zametání","Táhni koštětem v obloucích po podlaze"],
  ["Malování pokoje","Táhni válečkem svisle po zdi"],
  ["Fotografování","Přilož foťák k oku a stiskni spoušť"],
  ["Rybaření","Hoď udicí a trpělivě čekej se zabodnutým prutem"],
  ["Skákání přes švihadlo","Točí lano přes hlavu a přeskakuj"],
  ["Jízda na kole","Šlapej pedály a drž řídítka"],
  ["Lezení po žebříku","Stoupej ruku nohu nahoru s pohledem vzhůru"],
  ["Otevírání dárku","Trhej papír netrpělivě a vyjekni radostí"],
  ["Sekání trávy","Tlač sekačku vpřed v rovných pruzích"],
  ["Plavání","Předveď kraul rukama a kopej nohama"],
  ["Sprchování","Naznač proud vody nad hlavou a mydli si tělo"],
  ["Oblékání","Provlékej ruce rukávy a zapínej knoflíky"],
  ["Zavazování tkaniček","Sehni se a zauzluj tkaničku na mašli"],
  ["Zívání","Otevři ústa dokořán a zakryj je dlaní"],
  ["Utírání nádobí","Otírej talíř utěrkou dokola"],
  ["Zalévání květin","Nakláněj konev nad květináčem"],
  ["Kreslení","Tahej tužkou po papíře s přimhouřeným okem"],
  ["Smrkání","Přilož kapesník k nosu a hlasitě fukni"],
  ["Protahování se","Nataž paže vysoko a zakruž trupem"],
  ["Skládání oblečení","Přehýbej triko na půl a uhlazuj rukávy"],
  ["Vysoušení vlasů","Mávej fénem kolem hlavy a prohrabuj si vlasy"],
  ["Mávání na rozloučenou","Zvedni ruku a vlň dlaní ze strany na stranu"],
  ["Objímání","Rozpaž a přitáhni si někoho k hrudi"],
  ["Podávání ruky","Napřáhni dlaň a potřes s úsměvem"],
  ["Klepání na dveře","Zaklep kotníky prstů dvakrát o vzduch"],
  ["Škrábání se","Škrábej se na hlavě zamyšleně"],
  ["Poslouchání hudby","Kejvej hlavou do rytmu se sluchátky na uších"],
  ["Foukání na horké jídlo","Nabírej lžíci a foukej na ni, než ji ochutnáš"],
  ["Balení tašky","Skládej věci do batohu a zapínej zip"],
  ["Zavírání okna","Přitáhni k sobě okenní křídlo a zaklapni ho"]
 ],
 2: [
  ["Stopování","Vystrč palec u silnice a hleď na projíždějící auta"],
  ["Balení kufru","Skládej oblečení a sedni si na kufr, aby se zavřel"],
  ["Věšení prádla","Připínej kolíčky na šňůru kus po kuse"],
  ["Sázení stromu","Vykopej jamku a zasyp kořínky hlínou"],
  ["Dojení krávy","Střídavě tahej za neviditelné vemeno"],
  ["Střílení z luku","Napni tětivu k líci a vypusť šíp"],
  ["Žonglování","Přehazuj rukama tři neviditelné míčky do vzduchu"],
  ["Sekání dřeva","Zvedni sekeru nad hlavu a máchni na špalek"],
  ["Stavění stanu","Zapichuj kolíky a napínej stanovou plachtu"],
  ["Hraní na kytaru","Brnkej prsty po strunách a přidržuj hmatník"],
  ["Hraní na klavír","Ťukej prsty po neviditelných klávesách"],
  ["Hraní na bicí","Buš paličkami do bubnů a činelů"],
  ["Dirigování","Máchej rukama před orchestrem v rytmu"],
  ["Holení","Táhni břitvou po tváři a oplachuj ji"],
  ["Líčení se","Nanášej řasenku a rtěnku před zrcadlem"],
  ["Pletení svetru","Klapej dvěma jehlicemi a táhni vlnu"],
  ["Šití","Provlékej jehlu nití a stehuj látku"],
  ["Loupání cibule","Sundávej slupku a utírej si oči od slz"],
  ["Grilování","Otáčej špejlí nad plameny a mávej deštěm jisker"],
  ["Míchání koktejlu","Protřepej shaker a nalej do sklenky s ledem"],
  ["Venčení psa","Táhni vodítko a zastavuj se u každého sloupu"],
  ["Krmení miminka","Nabírej kašičku lžičkou a naznač let letadla"],
  ["Přebalování","Rozepni plenu a přilep novou"],
  ["Mytí oken","Stírej stěrkou sklo v kruzích"],
  ["Tapetování","Přejížděj kartáčem po tapetě a vyhlazuj bubliny"],
  ["Vysávání","Táhni vysavač sem tam po koberci"],
  ["Nakupování","Tlač vozík a naklad zboží do košíku"],
  ["Sáňkování","Sedni na sáně a řítě se dolů z kopce"],
  ["Malování vajíček","Namáčej štětec a barvi skořápku"],
  ["Zdobení stromečku","Věš ozdoby a naviuj řetěz kolem větví"],
  ["Stavění sněhuláka","Kutálej sníh na velké koule a sázej mrkev na nos"],
  ["Pouštění draka","Utíkej a popouštěj šňůru s drakem ve vzduchu"],
  ["Foukání bublin","Namoč kroužek a foukej mýdlové bubliny"],
  ["Skládání puzzle","Otáčej dílky a hledej, kam zapadají"],
  ["Hraní karet","Rozdávej karty a seřazuj je v ruce vějířem"],
  ["Výměna žárovky","Vyšroubuj starou žárovku a zašroubuj novou"],
  ["Výměna pneumatiky","Povol matky klíčem a zvedej auto zvedákem"],
  ["Vrtání do zdi","Přitiskni vrtačku a chvěj se s ní"],
  ["Zatloukání hřebíku","Přidržuj hřebík a buš kladivem"],
  ["Lakování nehtů","Táhni štětečkem laku po nehtu"],
  ["Sbírání hub","Skláněj se v lese a odřezávej houby nožem"],
  ["Trhání jablek","Natahuj se do korun a dávej plody do košíku"],
  ["Čištění bot","Otírej kartáčem boty do lesku"],
  ["Skládání prádla","Přehýbej kus po kuse na hromádku"],
  ["Šroubování nábytku","Utahuj šroubovákem panely podle návodu"],
  ["Zavařování","Plň sklenice a utahuj víčka"],
  ["Vaření svařáku","Míchej v hrnci a přivoněj ke koření"],
  ["Krmení ptáčků v zimě","Sypej semínka do krmítka na zahradě"],
  ["Broušení nožů","Táhni čepel opakovaně přes brousek"],
  ["Mletí kávy","Otáčej klikou mlýnku a přivoněj k vůni"],
  ["Umývání auta","Drhni houbou karoserii a oplachuj hadicí"],
  ["Šlapání na kole do kopce","Tlač na pedály a supěj do kopce"],
  ["Pečení chleba","Hněť těsto a vkládej bochník do trouby"],
  ["Klepání koberce","Buš tlukačkou do zavěšeného koberce, ať prášek lítá"],
  ["Sekání sekačkou svahu","Tlač sekačku šikmo do kopce s úsilím"],
  ["Čistění kola bicyklu","Otáčej pedálem a maž řetěz hadrem"],
  ["Nafukování matrace","Foukej do ventilku, dokud se matrace nenapne"]
 ],
 3: [
  ["Meditace","Seď se zkříženýma nohama a dýchej pomalu se zavřenýma očima"],
  ["Náměsíčnost","Kráčej strnule vpřed s nataženýma rukama a zavřenýma očima"],
  ["Ochutnávání vína","Zakruž sklenkou, přičichni a usrkni"],
  ["Hypnotizování","Houpej kyvadlem před cizíma očima a mluv monotónně"],
  ["Výběr z bankomatu","Zasuň kartu, naťukej kód a počkej na bankovky"],
  ["Parkování couváním","Otoč se přes rameno a couvej s natáčením volantu"],
  ["Zaklínání hada","Hraj na flétnu a nech hada vylézt z košíku"],
  ["Chůze po laně","Rozpaž ruce pro rovnováhu a opatrně přešlapuj"],
  ["Břišní tanec","Vlň bocích a třes pánví do rytmu"],
  ["Stepování","Buš rychle podpatky a špičkami do rytmu"],
  ["Moonwalk","Klouzej pozpátku, i když nohy jdou vpřed"],
  ["Origami","Přehýbej neviditelný papír do ostrých rohů"],
  ["Sprejování graffiti","Třepej plechovkou a stříkej ve velkých obloucích"],
  ["Sochání","Otesávej blok dlátem a odfukuj prach"],
  ["Kování podkovy","Buš kladivem do rozžhavené podkovy na kovadlině"],
  ["Dabování filmu","Mluv do mikrofonu a sleduj pohyby úst na obrazovce"],
  ["Kázání","Zvedej ruce k nebi a hřímej z kazatelny"],
  ["Uspávání dítěte","Kolébej v náručí a tichounce pobrukuj"],
  ["Břichomluvectví","Mluv bez pohybu rtů a pohybuj loutkou"],
  ["Čtení z ruky","Prohlížej dlaň a přejížděj prstem po linkách"],
  ["Věštění z koule","Krouž rukama nad koulí a zahleď se do ní"],
  ["Psaní na stroji","Buš prsty do kláves a cvakni na konci řádku"],
  ["Vysílání morseovky","Ťukej krátké a dlouhé signály klíčem"],
  ["Tetování","Vibruj strojkem po kůži v pomalých tazích"],
  ["Stříhání ovcí","Přidržuj ovci a stříhej vlnu velkými nůžkami"],
  ["Pletení copánků","Proplétej tři prameny vlasů přes sebe"],
  ["Chytání motýlů","Mávej sítí ve vzduchu za poletujícím motýlem"],
  ["Rozdělávání ohně","Tři dřívka o sebe a foukej do jiskřičky"],
  ["Chůze po žhavém uhlí","Kráčej rychle bosky přes rozžhavené uhlíky s napjatým výrazem"],
  ["Krocení divokého koně","Drž se pevně na hřbetu vzpínajícího se koně"],
  ["Kaligrafie","Táhni brkem elegantní tahy s nádechy a výdechy"],
  ["Balancování talíře na tyči","Roztoč talíř na špičce tyče a udržuj ho v pohybu"],
  ["Bubnování na djembe","Buš dlaněmi rychle do bubnu mezi koleny"],
  ["Recitace básně","Deklamuj s rukou na hrudi a důrazem na verše"],
  ["Malování na obličej","Táhni tenkým štětcem barevné vzory po tváři"],
  ["Skládání ubrousků do tvaru","Přehýbej látku do úhledného labutího tvaru"],
  ["Vyřezávání ze dřeva","Odřezávej nožem třísky ze špalku do tvaru"]
 ]
},
"Sporty": {
 1: [
  ["Fotbal","Kopni míč a předveď hlavičku"],
  ["Hokej","Klouzej na bruslích a švihni holí po puku"],
  ["Tenis","Odpal míček raketou přes síť"],
  ["Basketbal","Driblinguj míčem a hoď ho do koše"],
  ["Volejbal","Odbij míč nad hlavou a smeč přes síť"],
  ["Box","Kryj se pěstmi a odpal přímé rány"],
  ["Lyžování","Skrč se a klouzej ve výpadu ze svahu"],
  ["Bruslení","Kluzej po ledě dlouhými odrazy do stran"],
  ["Golf","Zamiř holí a švihni po míčku na tee"],
  ["Šipky","Zamiř a hoď šipku na terč"],
  ["Bowling","Rozeběhni se a kutálej kouli po dráze"],
  ["Ping-pong","Odpaluj míček malou pálkou přes stůl"],
  ["Cyklistika","Šlapej rychle v předklonu na kole"],
  ["Plavání (závodní)","Skoč z bloku a řež vodu prsou vpřed"],
  ["Sprint","Vyraz z nízkého startu a utíkej naplno"],
  ["Skok do dálky","Rozeběhni se a odraz se do vzduchu"],
  ["Šplh","Šplhej po tyči rukama nad sebe"],
  ["Přetahování lanem","Zapři se a tahej lano vší silou dozadu"],
  ["Kuželky","Kutálej kouli a srazte kuželky na konci dráhy"],
  ["Skákání v pytli","Vlez do pytle a skákej po dvou nohou vpřed"],
  ["Přehazovaná","Přehazuj míč přes síť oběma rukama"],
  ["Skoky přes gumu","Přeskakuj napnutou gumu mezi nohama kamarádů"],
  ["Frisbee","Švihni zápěstím a hoď talíř vodorovně"],
  ["Kroket","Ťukni paličkou do kuličky přes branky"],
  ["Ringo","Hoď gumový kroužek přes hlavu druhému hráči"]
 ],
 2: [
  ["Judo","Chyť soupeře za kimono a hoď ho přes bok"],
  ["Šerm","Vypadni kordem vpřed s výkřikem"],
  ["Lukostřelba","Napni tětivu a mikni na terč"],
  ["Veslování","Zabírej vesly souběžně dozadu v lodi"],
  ["Horolezectví","Šátrej rukama po skalní stěně a jisti se lanem"],
  ["Krasobruslení","Zatoč piruetu na jedné brusli s rukama nad hlavou"],
  ["Skok o tyči","Rozeběhni se s tyčí a vymršti se přes laťku"],
  ["Skok do výšky","Rozeběhni se obloukem a přehoupni se přes laťku zády"],
  ["Hod oštěpem","Rozeběhni se a švihni paží s oštěpem vpřed"],
  ["Hod kladivem","Roztoč se dokola s kladivem na řetězu a pusť ho"],
  ["Vzpírání","Zvedni obouruč těžkou činku nad hlavu"],
  ["Gymnastika","Udělej hvězdu a přemet na koberci"],
  ["Jóga","Zaujmi klidnou pozici na jedné noze s rukama nad hlavou"],
  ["Surfování","Balancuj na prkně a jeď na vlně"],
  ["Jachting","Tahej za lana a nastavuj plachtu do větru"],
  ["Baseball","Rozmáchni se pálkou po nadhozeném míči"],
  ["Kriket","Odpal míček širokou pálkou u branky"],
  ["Rugby","Sevři míč v podpaží a probíjej se soupeři"],
  ["Curling","Poklekni a vystřel kámen po ledu, kartáčuj před ním"],
  ["Biatlon","Lyžuj naplno, pak se zastav a zamiř puškou"],
  ["Vodní pólo","Plav a hoď míč jednou rukou do brány"],
  ["Badminton","Odpal košíček raketou vysokým obloukem"],
  ["Squash","Odpal míček raketou o zeď a vrať se pro odraz"],
  ["Skoky do vody","Odraz se z prkna a stočí tělo do vzduchu"],
  ["Snowboarding","Jeď bokem po prkně a skákej přes hrbolky"],
  ["Skateboarding","Odraz se nohou a skoč s prknem přes obrubník"],
  ["Florbal","Veď míček zahnutou hokejkou po podlaze"],
  ["Házená","Přihrávej míč jednou rukou a skákej ke brance"],
  ["Maraton","Běž vytrvale dlouhou trasu rovnoměrným tempem"],
  ["Kolečkové brusle","Kluzej na kolečkách s pažemi pro rovnováhu"],
  ["Sportovní střelba","Zamiř pistolí na terč a zadrž dech před výstřelem"],
  ["Motokros","Skloň se nad řídítka a skákej přes hrbol na motorce"],
  ["Závody formule","Drž volant pevně a předstírej řazení na rovince"],
  ["Aerobik","Cvič rytmicky s výskoky do hudby"],
  ["Balet","Stoupni si na špičky a udělej piruetu"],
  ["Rychlá chůze","Kráčej velmi rychle s kolébavými boky bez běhu"],
  ["Překážkový běh","Přeskakuj překážky bez zpomalení běhu"],
  ["Vrh koulí","Vystrč kouli od ramene mohutným švihem"],
  ["Hod diskem","Roztoč se a vypusť disk plochým letem"],
  ["Beach volejbal","Skákej v písku bosky a smeč míč přes síť"],
  ["Softball","Chytej velký míč do rukavice a odpaluj pálkou"],
  ["Krasojízda na kole","Balancuj na kole v pomalých kouzelných kruzích"],
  ["Triatlon","Plav, pak šlapej na kole a nakonec běž"],
  ["Cyklokros","Sesedni z kola a přenes ho přes překážku v běhu"],
  ["Karate","Vykřikni a předveď ostrý úder hranou dlaně"],
  ["Kickbox","Kombinuj údery pěstí s kopem nohou"],
  ["Zumba","Vlň boky do rytmické hudby s výskoky"],
  ["Vodní slalom","Projížděj kajakem mezi brankami na divoké vodě"],
  ["Windsurfing","Balancuj na prkně a drž plachtu proti větru"],
  ["Discgolf","Hoď létající talíř přesně do koše"],
  ["Skoky na koni","Cválej na koni a přeskoč překážku"],
  ["Přetlačování v páce","Zapři loket o stůl a přetlačuj soupeřovu ruku"]
 ],
 3: [
  ["Sumo","Dupni nohou, tleskni a narazi do soupeře břichem"],
  ["Pétanque","Hoď těžkou kouli tak, aby se přiblížila k malé kuličce"],
  ["Kanoistika","Vesluj jednostranným pádlem střídavě na obě strany"],
  ["Šachy","Přemýšlej nad figurkou a přesuň ji na políčko"],
  ["Parkour","Přeskakuj zídky a přeběhni po zdi"],
  ["Trojskok","Poskoč, přeskoč a nakonec se odraz do dálky"],
  ["Synchronizované plavání","Plav souhlasně s druhým a zvedej nohy nad hladinu"],
  ["Skoky na lyžích","Sjeď z můstku a rozlétni se v předklonu vzduchem"],
  ["Rychlobruslení","Kluzej v hlubokém předklonu s rukama za zády"],
  ["Pozemní hokej","Veď míček zahnutou holí při běhu po trávě"],
  ["Lakros","Chytej míček do síťky na dlouhé holi"],
  ["Bungee jumping","Skoč střemhlav dolů s lanem u kotníků"],
  ["Paragliding","Rozeběhni se s křídlem nad hlavou a vznes se"],
  ["Orientační běh","Sleduj mapu s buzolou a běž mezi kontrolami lesem"],
  ["Moderní gymnastika","Kruž stuhou nad hlavou v tanečním pohybu"],
  ["Skoky na trampolíně","Vyskakuj vysoko a udělej salto ve vzduchu"],
  ["Kitesurfing","Drž řídicí lišty draka a klouzej na prkně po vodě"],
  ["Vodní lyžování","Drž se madla za člunem a klouzej na lyžích"],
  ["Drezura koní","Veď koně jemnými pohyby uzdy do přesných kroků"],
  ["Šnorchlování","Plav s brýlemi a šnorchlem těsně pod hladinou"],
  ["Řecko-římský zápas","Chytej soupeře jen za horní část těla a povaluj ho"],
  ["Taekwondo","Vykopni vysoko nohou s výkřikem"],
  ["Boby","Skrč se v úzkých saních a řítě se zatáčkami"],
  ["Skeleton","Lehni si po hlavě na sáně a řítě se tratí"],
  ["Freediving","Nabery dech a potápěj se hluboko bez lahve"],
  ["Enduro","Projížděj motorku terénem přes kořeny a kameny"],
  ["Skialpinismus","Stoupej do kopce na lyžích s pásy pod nimi"],
  ["Rafting","Vesluj v týmu na nafukovacím člunu peřejemi"],
  ["Slackline","Balancuj bosky na pružícím popruhu mezi stromy"],
  ["Cyklistická časovka","Šlapej sólo na kole ze všech sil proti hodinám"],
  ["Sportovní lezení na rychlost","Vyšplhej co nejrychleji po umělé stěně s chyty"],
  ["Longboarding","Jeď na dlouhém prkně a zatoč velkými oblouky"]
 ]
},
"Předměty": {
 1: [
  ["Deštník","Otevři neviditelný deštník nad hlavou"],
  ["Kartáček na zuby","Kmitej rukou tam a zpět před ústy"],
  ["Nůžky","Stříhej dvěma prsty jako čepelemi"],
  ["Kladivo","Buš pěstí shora dolů jako kladivem"],
  ["Telefon","Přilož ruku k uchu a mluv"],
  ["Brýle","Nasaď si prsty na oči jako obroučky"],
  ["Kniha","Drž otevřené dlaně a otáčej stránky"],
  ["Klíč","Otoč zápěstím jako v zámku"],
  ["Hodinky","Poklepej na zápěstí a ukazuj na čas"],
  ["Židle","Posaď se na neviditelnou sedačku"],
  ["Lžíce","Nabírej neviditelnou polévku a foukej na ni"],
  ["Nůž","Krájej pohybem ruky dopředu a dozadu"],
  ["Vidlička","Napíchni sousto a zvedni k ústům"],
  ["Hrnec","Míchej obsah vařečkou v neviditelném hrnci"],
  ["Polštář","Nadýchni a poklepej pěstí do polštáře"],
  ["Zrcadlo","Prohlížej se a upravuj vlasy před neviditelnou plochou"],
  ["Míč","Odraz míč o zem opakovaně dlaní"],
  ["Balónek","Nafoukni tváře a zavaž konec balónku"],
  ["Svíčka","Zapal sirkou knot a sfoukni plamínek"],
  ["Kytara","Brnkej po strunách a přidržuj hmatník"],
  ["Tužka","Piš krátkými tahy a olízni si špičku"],
  ["Hřeben","Přejížděj zuby hřebenu vlasy"],
  ["Ručník","Utírej si obličej a tělo velkým kusem látky"],
  ["Mýdlo","Pěň si dlaně a vytvoř bubliny"],
  ["Peněženka","Otevři a přepočítej neviditelné bankovky"],
  ["Lampa","Cvakni vypínačem a stíň si oči od světla"],
  ["Postel","Lehni si a přetáhni přes sebe přikrývku"],
  ["Koště","Zameť podlahu širokými tahy"],
  ["Rukavice","Navlékni si prsty postupně do rukavice"],
  ["Čepice","Nasaď si čepici a stáhni ji přes uši"],
  ["Šála","Omotej si látku několikrát kolem krku"],
  ["Batoh","Provlékni ruce popruhy a hoď si ho na záda"],
  ["Pero","Odklopni víčko a piš plynulým tahem"],
  ["Sešit","Otevři a listuj popsanými stránkami"],
  ["Talíř","Drž rovně a nes plný jídla"],
  ["Sklenice","Zvedni a napij se doušku"],
  ["Deka","Rozprostři a zabal se do ní na gauči"],
  ["Kbelík","Nes plný vody a nakloň ho k vylití"],
  ["Bota","Navlékni na nohu a zavaž tkaničku"],
  ["Slunečník","Rozevři nad hlavou a zapíchni do písku"],
  ["Pantofle","Šoupej nohama v měkké obuvi po bytě"]
 ],
 2: [
  ["Vysavač","Táhni hubici sem a tam po koberci s bzučením"],
  ["Mikrovlnka","Otevři dvířka, vlož talíř a natoč knoflík"],
  ["Fén","Mávej horkým vzduchem kolem vlasů"],
  ["Šroubovák","Otáčej zápěstím jako při utahování šroubu"],
  ["Pila","Táhni rukou tam a zpět jako při řezání dřeva"],
  ["Sekera","Zvedni a máchni sekerou na špalek"],
  ["Lopata","Zapichuj a nabírej zeminu na lopatu"],
  ["Hrábě","Táhni hrábě k sobě a shrabuj listí"],
  ["Konev","Nakláněj konev nad květinami"],
  ["Dalekohled","Přilož obě ruce k očím a přibliž kruhy"],
  ["Mikroskop","Přimhouř jedno oko a nakláněj se nad čočku"],
  ["Kompas","Drž rovně na dlani a sleduj otáčející se střelku"],
  ["Fotoaparát","Přilož k oku a mačkni spoušť s bleskem"],
  ["Sluchátka","Nasaď na uši a kejvej hlavou do rytmu"],
  ["Klavír","Hraj prsty po neviditelných klávesách"],
  ["Buben","Buš paličkami rytmicky před sebou"],
  ["Trumpeta","Přilož k ústům a mačkej ventily"],
  ["Housle","Táhni smyčcem přes struny pod bradou"],
  ["Stan","Zapichuj kolíky a napínej plachtu nad hlavou"],
  ["Spacák","Vlez si do pytle a zataž zip až k bradě"],
  ["Baterka","Cvakni a posvěť si kruhem světla kolem"],
  ["Zapalovač","Cvakni palcem a zapal plamínek"],
  ["Vývrtka","Zašroubuj do zátky a táhni ji ven"],
  ["Otvírák na konzervy","Zaklesni na okraj plechovky a otáčej dokola"],
  ["Struhadlo","Táhni sýr přes struhadlo dolů"],
  ["Váleček na těsto","Válej těsto oběma rukama tam a zpět"],
  ["Šlehač","Krouž rychle šlehačem v misce"],
  ["Teploměr","Vlož si teploměr pod paži a čekej na pípnutí"],
  ["Injekce","Napíchni jehlou a zatlač píst"],
  ["Berle","Podepírej se pod paží a poskakuj na jedné noze"],
  ["Mikrofon","Přilož k ústům a klepni prstem, jestli funguje"],
  ["Píšťalka","Foukni ostře a zapískej"],
  ["Zvon","Zhoupni rukou zvon ze strany na stranu"],
  ["Flétna","Přilož k rtům nakřivo a foukej přes otvor"],
  ["Saxofon","Přidržuj šikmo dolů a mačkej klapky"],
  ["Trakař","Zvedni rukojeti a tlač jednokolku vpřed"],
  ["Kosa","Švihni dlouhým obloukem u nohou po trávě"],
  ["Vidle","Nabírej seno na dlouhé zuby a přehazuj"],
  ["Prak","Napni gumu mezi prsty a vystřel"],
  ["Meč","Sekej a bodej neviditelnou čepelí"],
  ["Štít","Kryj se rovnou deskou před ranami"],
  ["Helma","Nasaď si na hlavu a upevni řemínek pod bradou"],
  ["Koloběžka","Odrážej se jednou nohou a stůj na druhé"],
  ["Kleště","Sevři a stiskni něco mezi čelistmi kleští"],
  ["Pinzeta","Sevři drobný předmět dvěma prsty jako čelistmi"],
  ["Lupa","Přibliž kulaté sklo k oku a zvětšuj"],
  ["Řetězová pila","Zatáhni za startér a veď burácející pilu dřevem"],
  ["Svěrák","Otáčej rukojetí a sevři předmět mezi čelisti"],
  ["Pájka","Přilož žhavou špičku a roztav cínovou nit"],
  ["Žebřík","Přistav ho ke zdi a stoupej po příčkách"],
  ["Kolébka","Houpej jemně dopředu a dozadu s miminkem"],
  ["Houpačka","Odraž se nohama a houpej se dopředu dozadu"],
  ["Rybářský prut","Švihni prutem dozadu a hoď vlasec vpřed"],
  ["Lucerna","Rozsviť plamínek uvnitř a nes ji za držadlo"],
  ["Kufřík","Cvakni zámky a otevři plochý kufřík"],
  ["Pistole na hřebíky","Přilož k desce a stiskni spoušť s ránou"],
  ["Kladkostroj","Táhni za lano a sleduj, jak se břemeno zvedá"],
  ["Skládací nůž","Vyklop čepel z rukojeti nehtem"],
  ["Vrtačka","Přitiskni a chvěj se s vrtačkou do zdi"],
  ["Hasák","Sevři trubku a otoč ji silou proti závitu"],
  ["Svinovací metr","Vytáhni pásku a nech ji se svinout zpět"],
  ["Nůžky na drát","Sevři drát mezi čelisti a přestřihni ho"]
 ],
 3: [
  ["Periskop","Dívej se do trubice a nakláněj zrcátka nahoru dolů"],
  ["Kyvadlo","Houpej rukou pravidelně ze strany na stranu"],
  ["Metronom","Kývej vzpřímeným prstem přesně v rytmu"],
  ["Semafor","Střídej barvy rukou - červená, oranžová, zelená"],
  ["Maják","Otáčej rukou nad hlavou jako kroužící světlo"],
  ["Katapult","Napni rameno a vymršti náklad do dálky"],
  ["Padák","Rozprostři ruce nad hlavou a snášej se pomalu dolů"],
  ["Bumerang","Švihni zápěstím a čekej, až se vrátí zpět"],
  ["Harfa","Přejížděj prsty svisle po neviditelných strunách"],
  ["Dudy","Mačkej vak pod paží a foukej do troubele"],
  ["Akordeon","Roztahuj a stlačuj měchy mezi rukama"],
  ["Kolovrat","Šlapej pedál a přidržuj nit při předení"],
  ["Přesýpací hodiny","Otoč a sleduj sypající se písek dolů"],
  ["Rentgen","Postav se nehybně, zatímco skrz tebe prosvítí paprsek"],
  ["Detektor kovů","Kruž tyčí nízko nad zemí a poslouchej pípání"],
  ["Hromosvod","Ukazuj svisle vzhůru na tyč na střeše"],
  ["Trezor","Otáčej ciferníkem sem a tam, než zacvakne"],
  ["Past na myši","Napni páčku a strhni ji prudkým klapnutím"],
  ["Gramofon","Polož jehlu na točící se desku a poslouchej"],
  ["Globus","Roztoč kouli prstem a ukazuj na kontinenty"],
  ["Kaleidoskop","Přilož oko k trubici a otáčej ji pro nové vzory"],
  ["Hasicí přístroj","Vytrhni pojistku a stříkej pěnu na plameny"],
  ["Defibrilátor","Přilož elektrody na hrudník a zvolej uhni"],
  ["Stetoskop","Nasaď si sluchátka a přiložuj membránu na hrudník"],
  ["Čínské hůlky","Sevři dvě tyčinky mezi prsty a nabírej sousto"],
  ["Houpací křeslo","Houpej se plynule dopředu a dozadu vsedě"],
  ["Sextant","Přilož k oku a měř úhel mezi obzorem a hvězdou"],
  ["Barometr","Poklep na ciferník a sleduj kolísání ručičky"],
  ["Anemometr","Nastav miskovité lopatky do větru a sleduj otáčky"],
  ["Seismograf","Sleduj jehlu kreslící klikaté čáry při otřesu"],
  ["Polygraf","Připoj hadičky na hrudník a sleduj vykreslující se křivku"],
  ["Rovnoramenné váhy","Přikládej závaží na misky, dokud se nevyrovnají"],
  ["Sluneční hodiny","Sleduj stín ukazatele klouzající po ciferníku"],
  ["Vodní hodiny","Sleduj kapající vodu přetékající mezi nádobami"],
  ["Enigma (šifrovací stroj)","Ťukej do kláves a sleduj rozsvěcující se zašifrovaná písmena"]
 ]
},
"Emoce a stavy": {
 1: [
  ["Radost","Skákej vysoko s rozzářeným úsměvem a rozpaženýma rukama"],
  ["Smutek","Svěš ramena a otírej si slzu z tváře"],
  ["Vztek","Zatni pěsti a dupej nohou o zem"],
  ["Strach","Cukni se dozadu s rukama před obličejem"],
  ["Únava","Svěš víčka a vleč nohy pomalu za sebou"],
  ["Nuda","Zívej a bezmyšlenkovitě klepej prsty o stůl"],
  ["Překvapení","Otevři ústa a ustup s rukama u tváří"],
  ["Pláč","Otírej si oči a popotahuj nosem"],
  ["Smích","Drž se za břicho a otřásej se v záchvatech"],
  ["Hlad","Polož ruku na břicho a předveď kručení"],
  ["Žízeň","Vyplázni jazyk a ukazuj na vyprahlé hrdlo"],
  ["Zima (mrznutí)","Objímej se pažemi a klepej zuby"],
  ["Horko","Ovívej se rukou a otírej si čelo"],
  ["Bolest zubů","Přidržuj si tvář a syč bolestí"],
  ["Zamilovanost","Kresli srdíčko ve vzduchu a povzdechni si"],
  ["Ospalost","Klimbej hlavou a bojuj s klesajícími víčky"],
  ["Lechtání","Kroutíš se a vypískni s uhýbáním"],
  ["Svědění","Drbej se zuřivě na různých místech těla"],
  ["Bolest hlavy","Přitiskni si dlaně ke spánkům a přivírej oči"],
  ["Bolest břicha","Skrč se a přidržuj si rukama břicho"],
  ["Rýma","Popotahuj a otírej si nos kapesníkem"],
  ["Kašel","Přikryj si ústa loktem a prudce se zhrbi"],
  ["Horečka","Otírej si zpocené čelo a chvěj se"],
  ["Bolest v krku","Přidržuj si hrdlo a polykej s bolestivou grimasou"],
  ["Bolest zad","Narovnávej se pomalu s rukou na kříži"],
  ["Ucpaný nos","Dýchej otevřenými ústy a mni si nos"],
  ["Zvracení","Skloň se nad umyvadlo a prudce sebou trhni"],
  ["Zpocenost","Otírej si čelo a ovívej si tvář"],
  ["Roztřesenost","Rozklepej se po celém těle jako v zimě"],
  ["Malátnost","Ochable se opři o zeď a přivírej oči"],
  ["Otupělost","Zírej prázdně před sebe bez výrazu"]
 ],
 2: [
  ["Žárlivost","Mrkej úkosem a založ si ruce s nafouknutými tvářemi"],
  ["Stud","Zakryj si tvář rukama a schovej se za rameno"],
  ["Nervozita","Kousej si nehty a přešlapuj z nohy na nohu"],
  ["Zklamání","Svěs ramena a povzdechni si s pohledem dolů"],
  ["Pýcha","Vypni hruď a hrdě vzhůru zvedni bradu"],
  ["Znechucení","Zkřiv obličej a odtáhni se s rukou na ústech"],
  ["Zvědavost","Nakloň hlavu a vytřeštěně nakoukni blíž"],
  ["Netrpělivost","Poklepávej nohou a koukej na hodinky"],
  ["Úleva","Vydechni zhluboka a svěs ramena s úsměvem"],
  ["Vyčerpání","Skácej se na židli a lapej po dechu"],
  ["Nadšení","Poskakuj a tleskej rukama nad hlavou"],
  ["Tréma","Otírej si zpocené dlaně a přešlapuj před vystoupením"],
  ["Závrať","Zapotácej se a chytej se něčeho pro rovnováhu"],
  ["Škytavka","Trhni sebou a přikryj si ústa při každém škytnutí"],
  ["Kýchání","Zakryj si nos a prudce hlavou trhni dopředu"],
  ["Alergie","Kýchej opakovaně a drbej si zarudlé oči"],
  ["Nespavost","Převaluj se v posteli a koukej na hodiny"],
  ["Mořská nemoc","Zezelenej a drž se za žaludek při houpání"],
  ["Opilost","Vrávorej a mluv s jazykem za zuby"],
  ["Zmatenost","Rozhlížej se s rukama v bok a svraštěným čelem"],
  ["Stres","Chvátej a mni si spánky oběma rukama"],
  ["Panika","Pobíhej zmateně s rukama nad hlavou"],
  ["Nevolnost","Přidržuj si ústa a zezelenej"],
  ["Křeč v noze","Zkřiv se bolestí a masíruj si lýtko"],
  ["Vyplašenost","Sebou trhni a rozhlížej se s rukama nahoře"],
  ["Podráždění","Přivírej oči a mávej rukou na odbyto"],
  ["Skleslost","Klesni na židli s prázdným pohledem k zemi"],
  ["Rozechvění","Chvěj se rukama a přerývaně dýchej"],
  ["Ohromení","Zůstaň strnule stát s otevřenou pusou"],
  ["Trapnost","Zarazi se v půli pohybu a začerveněj se"],
  ["Nedočkavost","Poskakuj na místě a natahuj krk dopředu"],
  ["Otrávenost","Obrať oči v sloup a povzdechni si otráveně"]
 ],
 3: [
  ["Nostalgie","Zahleď se do dálky s jemným úsměvem nad vzpomínkou"],
  ["Závist","Přimhouř oči a ukaž na cizí věc se zaťatou pěstí"],
  ["Rozpaky","Přešlapuj a nervózně si mni ruce s uhýbajícím pohledem"],
  ["Melancholie","Opři si hlavu o dlaň a vzdychej u okna"],
  ["Euforie","Rozhoď ruce a vytoč se dokola s úsměvem od ucha k uchu"],
  ["Paranoia","Rychle se ohlížej přes rameno a přitiskni se ke zdi"],
  ["Déjà vu","Zarazi se uprostřed pohybu se zmateným výrazem, jako už to znáš"],
  ["Klaustrofobie","Tiskni ruce na neviditelné stěny kolem sebe a lapej po dechu"],
  ["Pocit viny","Sklop oči a nervózně si mni prsty"],
  ["Soucit","Polož ruku na srdce a nakloň hlavu s láskyplným pohledem"],
  ["Vděčnost","Přilož ruce k hrudi a ukloň se s vděčným úsměvem"],
  ["Zamyšlenost","Podepři si bradu prstem a hleď do prázdna"],
  ["Roztržitost","Hledej něco v kapsách, co držíš v ruce"],
  ["Podezíravost","Přimhouř jedno oko a nedůvěřivě si někoho měř"],
  ["Sarkasmus","Zvedni obočí a pomalu zatleskej s kyselým úsměvem"],
  ["Nerozhodnost","Kmitej pohledem mezi dvěma stranami a krč rameny"],
  ["Zoufalství","Chytej se za hlavu a klesni na kolena"],
  ["Optimismus","Ukazuj palec nahoru se širokým úsměvem k nebi"],
  ["Pesimismus","Krč rameny a mávni rukou, že to stejně nevyjde"],
  ["Lhostejnost","Krč rameny s prázdným výrazem a odvrať se"],
  ["Osamělost","Objímej se pažemi a hleď smutně do prázdna kolem"],
  ["Dojetí","Přilož ruku k srdci a otírej si slzu dojetí"],
  ["Amnézie","Poklepávej si na čelo a bezradně krč rameny"],
  ["Splín","Povzdechni si a bezcílně civěj z okna do deště"],
  ["Vzdor","Zkřiž ruce na hrudi a odmítavě zavrť hlavou"],
  ["Odevzdanost","Svěs ramena a bezmocně rozhoď ruce"],
  ["Nadutost","Zvedni nos a přezíravě přejeď pohledem kolem"],
  ["Zahanbení","Sklop hlavu a schovej tvář do dlaní"],
  ["Blaženost","Zavři oči s blaženým úsměvem a protáhni se jako po probuzení"],
  ["Rozmrzelost","Nakrč nos a otráveně obrať oči v sloup"]
 ]
},
"Pohádky a film": {
 1: [
  ["Popelka","Zameť podlahu a v půlnoci uteč bez střevíčku"],
  ["Červená Karkulka","Nes košík a kráčej lesem k babiččině chaloupce"],
  ["Sněhurka","Kousni do jablka a upadni do spánku"],
  ["Vodník","Plácej žabíma rukama a fajfku si přidrž u úst"],
  ["Čert","Zavrč, dupej kopyty a máchej ocasem"],
  ["Anděl","Roztáhni křídla za zády a plachtě se vznášej"],
  ["Drak","Chrlí oheň z tlamy a mávej křídly"],
  ["Princezna","Nadzvedni sukni a kráčej s rovnou hlavou"],
  ["Král","Nasaď si korunu a mávej pomyslným žezlem"],
  ["Rytíř","Zvedni pomyslný meč a buš pěstí do brnění"],
  ["Čarodějnice","Vysedni na koště a zakřič kouzelnou formuli"],
  ["Duch","Vlaj rukama a proplouvej se zavytím zdí"],
  ["Upír","Vycen zuby a schovej se za pláštěnku"],
  ["Pirát","Skákej po jedné noze a přidrž si klapku na oku"],
  ["Superman","Vzleť s pěstí napřed a pláštěm vlajícím vzadu"],
  ["Spiderman","Vystřel síť ze zápěstí a plaz se po zdi"],
  ["Batman","Roztáhni plášť jako křídla a vrhni se ze střechy"],
  ["Mikuláš","Hlaď si dlouhý vous a rozdávej z pytle"],
  ["Obr","Kráčej těžkými kroky a shlížej dolů na trpaslíky"],
  ["Víla","Zamávej hůlčičkou a poletuj s křidélky"],
  ["Loupežník","Nasaď si šátek přes obličej a hrozivě mávej mečem"],
  ["Mumie","Kráčej strnule s nataženýma rukama v obvazech"],
  ["Kostlivec","Chřestivě klapej klouby a cvakni čelistí"],
  ["Zombie","Vlekej nohy a natahuj ruce s prázdným pohledem"],
  ["Ježíšek","Nes dárky tichým krokem a zvoň zvonečkem"],
  ["Trpaslík","Kráčej v podřepu s dlouhým vousem a špičatou čepicí"],
  ["Skřítek","Poskakuj potichu na špičkách s ušima nastraženýma"],
  ["Sněhulák","Stůj nehybně s kbelíkem na hlavě a mrkví místo nosu"],
  ["Jednorožec","Klušej s prstem na čele jako s rohem"],
  ["Robot","Pohybuj se trhaně kostrbatými pohyby"],
  ["Mimozemšťan","Kráčej rozvážně a ukazuj antény na hlavě"],
  ["Kouzelný džin","Vynoř se z lampy v obláčku kouře se zkříženýma rukama"],
  ["Netvor pod postelí","Plaz se nízko při zemi a vycen zuby ze tmy"]
 ],
 2: [
  ["Harry Potter","Máchej hůlkou a naznač blesk na čele"],
  ["Shrek","Dupej bahnem a mračí se z bažiny"],
  ["Tarzan","Buš se do hrudi a houpej se na liáně s pokřikem"],
  ["Robin Hood","Napni luk a vystřel šíp z lesa"],
  ["Peter Pan","Vzleť s rukama v bok a nezestárni"],
  ["Pinocchio","Přilož si ruku k nosu, jak roste s každou lží"],
  ["Sněhová královna","Rozhoď ruce a nech sníh a led vytrysknout"],
  ["Zlatovláska","Rozčesávej si dlouhé zlaté vlasy hřebenem"],
  ["Rumcajs","Nasaď klobouk s pírkem a kráčej lesem s trumpetou"],
  ["Krteček","Vyhrabávej se z hlíny a rozhlížej se malýma ručkama"],
  ["Ferda Mravenec","Kráčej rázně jako brouk s knoflíkem na klopě"],
  ["Maxipes Fík","Skákej vesele po čtyřech s vyplazeným jazykem"],
  ["Zorro","Naznač písmeno Z mečem do vzduchu a nasaď masku"],
  ["James Bond","Naznač pistoli a upravuj si motýlka"],
  ["King Kong","Buš se do hrudi na vrcholu mrakodrapu"],
  ["Godzilla","Dupej těžce a chrlí ohnivý paprsek z tlamy"],
  ["Yoda","Kráčej nahrbeně o holi a mluv obráceným slovosledem"],
  ["Darth Vader","Dýchej hlasitě a máchej neviditelným světelným mečem"],
  ["Mimoň","Poskakuj vesele a žvatlej nesrozumitelně"],
  ["Elsa (Ledové království)","Rozhoď ruce a nech vyrůst ledový hrad"],
  ["Mořská panna","Plav rukama a švihej ocasem místo nohou"],
  ["Sherlock Holmes","Prohlížej lupou stopy s dýmkou v ústech"],
  ["Vlkodlak","Skrč se, naznač drápy a zavyj k měsíci"],
  ["Herkules","Zvedni obrovský balvan nad hlavu s napjatými svaly"],
  ["Aladin","Vytři lampu a vyleť na kouzelném koberci"],
  ["Kocour v botách","Poskakuj po zadních v botách a smekni klobouk"],
  ["Baron Prášil","Sedni na dělovou kouli a předstírej let vzduchem"],
  ["Hurvínek","Pohybuj se trhaně jako loutka na nitkách"],
  ["Pat a Mat","Kutálej se s nešikovným nářadím kolem sebe"],
  ["Bob a Bobek","Skákej po dvou jako králík s dlouhýma ušima"],
  ["Rákosníček","Houpej se na rákosí a foukej na píšťalku"],
  ["Večerníček","Nasaď si čepičku a mávej na dobrou noc"],
  ["Asterix","Napij se z kouzelného kotlíku a napni svaly"],
  ["Obelix","Nes obrovský menhir na zádech s obřím břichem"],
  ["Krakonoš","Kráčej lesem s dlouhým vousem a hůlkou, ochraňuj zvěř"],
  ["Otesánek","Nafukuj břicho a předstírej, že spolykáš vše kolem"],
  ["Ježibaba","Kulhej o holi a míchej lektvar v kotli"],
  ["Tři prasátka","Stav dům ze slámy, dřeva a cihel a schovej se před vlkem"],
  ["Iron Man","Napřáhni dlaň dopředu a naznač výstřel z brnění"],
  ["Hulk","Nafoukni svaly a roztrhni pomyslné triko vzteky"],
  ["Wonder Woman","Zkřiž zápěstí jako s kouzelnými náramky a roztoč lasem"],
  ["Kapitán Amerika","Nadhoď kulatý štít a chyť ho zpátky"],
  ["Thor","Rozmáchni se kladivem a přivolej blesk"],
  ["Simba (Lví král)","Vyskoč na skálu a zařvi do savany"],
  ["Nemo (Hledá se Nemo)","Plav malou ploutvičkou a schovávej se v korálech"]
 ],
 3: [
  ["Golem","Kráčej strnule z hlíny s tabulkou na čele"],
  ["Frankenstein","Kráčej strnule s rukama napřed a šrouby na krku"],
  ["Dracula","Zahal se pláštěm a vycen zuby ke krku oběti"],
  ["Gandalf","Podepři se o hůl a zvedni ji proti nepříteli, ať neprojde"],
  ["Glum","Plaz se po čtyřech a šeptej si o svém pokladu"],
  ["Hobit","Kráčej bosky drobnými krůčky s chlupatýma nohama"],
  ["Terminátor","Kráčej strnule a nastav palec nahoru"],
  ["Rocky","Boxuj do vzduchu a vyběhni schody s rukama nahoře"],
  ["Indiana Jones","Švihni bičem a nasaď si klobouk před útěkem"],
  ["Jack Sparrow","Vrávorej opile a přidržuj si kompas"],
  ["Forrest Gump","Běž rovnoměrně dlouhé kilometry bez zastavení"],
  ["Mary Poppins","Otevři deštník a vzlétni s ním do oblak"],
  ["Střihoruký Edward","Stříhej vzduch prsty jako nůžkami místo rukou"],
  ["Čaroděj ze země Oz","Schovej se za oponou a promlouvej mohutným hlasem"],
  ["E.T.","Nataž prst ke svítícímu prstu druhého a šeptej domů"],
  ["Neo (Matrix)","Ukloň se dozadu, aby ti nade hlavou proletěly kulky"],
  ["Willy Wonka","Otevři kouzelnou továrnu mávnutím hůlky a usměj se tajemně"],
  ["Švejk","Šoupej nohama a s nevinným úsměvem vyprávěj historky"],
  ["Kapitán Hák","Máchej hákem místo ruky a hrozi kapitánskou pistolí"],
  ["Don Quijote","Napřáhni kopí na koni proti větrnému mlýnu"],
  ["Tři mušketýři","Zkřiž kord s výkřikem hesla o jednotě"],
  ["Robinson Crusoe","Rozdělávej oheň na pustém ostrově a hledej stopu v písku"],
  ["Gulliver","Lež svázaný provázky drobných lidiček na zemi"],
  ["Charlie Chaplin","Kráčej komicky se špičkami ven a s hůlkou v ruce"],
  ["Mr. Bean","Rozhlížej se nešikovně a dělej trapné grimasy"],
  ["Rambo","Naviaž si čelenku a plaz se s nožem mezi zuby"],
  ["Vinnetou","Nasaď si čelenku s pírkem a nes luk s šípy"],
  ["Frodo","Sevři neviditelný prsten na řetízku a plaz se úkradkem"],
  ["Legolas","Napni luk vestoje na jedno koleno a mrkni při míření"],
  ["Homer Simpson","Poplácej se po bříšku a zavolej hlasitě d'oh"],
  ["Scooby Doo","Klušej po čtyřech s ušima na zemi a čenichej stopu"],
  ["Chewbacca","Zavrč zvláštním brumláním a předveď chlupaté paže"],
  ["Jabba the Hutt","Plaz se vpřed jako beztvará hmota bez nohou"],
  ["Gru (Já, padouch)","Kráčej vysokou postavou v černém plášti a zlomyslně se šklebí"],
  ["Popelčina zlá macecha","Hrozivě ukazuj prstem a přezíravě ohrnuj nos"],
  ["Karkulčin vlk","Skryj se pod peřinou a vycen zuby s otázkou, proč máš tak velké oči"]
 ]
},
"Jídlo a vaření": {
 1: [
  ["Špagety","Namotávej těstoviny na vidličku a nasávej konec"],
  ["Zmrzlina","Olizuj kopeček, než ti steče po ruce"],
  ["Banán","Oloupej slupku pruh po pruhu a ukousni"],
  ["Jablko","Ukousni šťavnaté sousto s hlasitým křupnutím"],
  ["Citron","Ukousni a stáhni obličej kyselostí"],
  ["Popcorn","Házej si kousky do pusy jeden po druhém"],
  ["Pizza","Ukroj trojúhelník a natáhni sýrové vlákno"],
  ["Polévka","Fouká na lžíci a srkej hlasitě"],
  ["Lízátko","Olizuj kulatý bonbón na tyčince"],
  ["Žvýkačka","Žvýkej dokola a nafoukni velkou bublinu"],
  ["Rohlík","Odlamuj kousky a chroupej je"],
  ["Chléb","Ukroj plátek a namaž ho pomyslným máslem"],
  ["Hranolky","Nabírej po jednom prstama a namáčej v kečupu"],
  ["Dort","Uřízni krajíc a olizuj polevu z prstů"],
  ["Čokoláda","Odlámej kousek tabulky a nech ho rozplynout na jazyku"],
  ["Bonbón","Rozbal papírek a vhoď si bonbón do pusy"],
  ["Med","Naber medovou lžičku a nech ji stékat do pusy"],
  ["Mléko","Nalévej ze sklenice a napij se s bílým knírkem"],
  ["Čaj","Foukej na horký šálek a usrkni"],
  ["Jogurt","Nabírej lžičkou z kelímku"],
  ["Sušenka","Namáčej sušenku do mléka a rychle ji sněz, než změkne"],
  ["Sirup","Nalévej hustou tekutinu do sklenice s vodou"],
  ["Vafle","Skládej vrstvy a polévej je šlehačkou"],
  ["Máslo","Roztírej kostku na plátek chleba"],
  ["Rajče","Ukousni šťavnaté a utírej si stříkající šťávu"],
  ["Okurka","Nakrájej na kolečka a chroupej"],
  ["Hruška","Ukousni šťavnaté sousto se šťávou stékající po bradě"]
 ],
 2: [
  ["Palačinky","Otoč palačinku ve vzduchu a posyp ji cukrem"],
  ["Hamburger","Skládej vrstvy a otevři pusu doširoka na kousnutí"],
  ["Sushi","Namáčej kousek do sojové omáčky hůlkami"],
  ["Grilované kuře","Ohryzávej stehno drženo oběma rukama"],
  ["Vejce naměkko","Ťukni lžičkou o skořápku a vyškrábni žloutek"],
  ["Kukuřice na klasu","Drž klas oběma rukama a ohryzávej ho po řadách"],
  ["Meloun","Ukrajuj plátky a vyplivuj pecky"],
  ["Kokos","Buš kladivem o skořápku a pij mléko brčkem"],
  ["Ananas","Loupej trnitou slupku a ukusuj šťavnaté kolečko"],
  ["Chilli paprička","Ukousni a chytej se za hořící pusu s vyplazeným jazykem"],
  ["Česnek","Rozmačkej stroukem a odežeň si odér rukou"],
  ["Cibule","Krájej a utírej si slzící oči"],
  ["Šlehačka","Vystřikuj z bombičky spirálu na dort"],
  ["Fondue","Napíchni kousek na vidlici a namáčej v roztaveném sýru"],
  ["Hot dog","Vlož párek do rohlíku a polij hořčicí"],
  ["Mléčný koktejl","Sáčej brčkem hustý nápoj se zvukem"],
  ["Taco","Naplň tortillu a snaž se ji sníst, než se rozsype"],
  ["Kebab","Ukrajuj maso z rožně a plň pita chléb"],
  ["Smažený sýr","Krájej křupavou strouhanku a natahuj tavený sýr"],
  ["Bramborák","Míchej strouhané brambory a smaž na pánvi"],
  ["Trdelník","Naviň těsto na tyč a obaluj v cukru nad ohněm"],
  ["Řízek","Naklepávej maso paličkou a obaluj ho v strouhance"],
  ["Špenát","Sbírej lístky a jez je s otevřenou pusou jako Pepek"],
  ["Kyselá okurka","Ukousni a stáhni obličej při kyselé chuti"],
  ["Pivo","Napěň si sklenici a smáni si pěnu z rtu"],
  ["Guláš","Míchej hustou omáčku a nabírej ji houskovým knedlíkem"],
  ["Knedlík","Krájej nití kolečka a máčej v omáčce"],
  ["Svíčková","Polévej maso krémovou omáčkou a přidávej brusinky"],
  ["Langoš","Potírej placku česnekem a posypávej sýrem"],
  ["Buchty","Plň těsto povidly a tvaruj do polštářků"],
  ["Rizoto","Míchej rýži v pánvi a přilévej vývar postupně"],
  ["Lasagne","Skládej vrstvy těstovin s omáčkou do pekáče"],
  ["Omeleta","Rozšlehej vejce a přehni omeletu na pánvi"],
  ["Vinná klobása","Opékej na grilu a nakrajuj s křupnutím"]
 ],
 3: [
  ["Kaviár","Nabírej malou lžičkou drobná zrnka na krekr"],
  ["Ústřice","Rozevři skořápku nožem a vysrkni obsah"],
  ["Šampaňské","Vystřel korek a nalévej pěnící nápoj do úzké sklenky"],
  ["Espresso","Vypij malý hustý šálek na ex a odfrkni"],
  ["Croissant","Trhej vrstvy rohlíčku a otřepávej drobky"],
  ["Tatarák","Míchej syrové maso s vejcem a mazi na topinku"],
  ["Šneci","Vytahuj masíčko z ulity malou vidličkou"],
  ["Cukrová vata","Namotávej vláknitý cukr na tyčinku"],
  ["Žebírka","Ohryzávej maso z kosti oběma rukama"],
  ["Tortilla","Zabaluj náplň do placky a skládej konce"],
  ["Pálivá křidélka","Ohryzávej křidélko a rychle popíjej vodu na hašení"],
  ["Opékání marshmallow","Napíchni na klacík a opatrně opékej nad ohněm"],
  ["Humr","Rozlámej klepeto kleštěmi a vytahuj maso"],
  ["Artyčok","Odlupuj lístek po lístku a okusuj základnu"],
  ["Flambování","Přelej alkoholem a zapal plameny nad pánví"],
  ["Zavařování marmelády","Míchej vroucí ovoce v hrnci a plň do sklenic"],
  ["Granátové jablko","Rozlomi plod a vyklepávej červená zrnka"],
  ["Karamelizace cukru","Míchej cukr na pánvi, dokud nezhnědne, a opatrně foukej na horko"],
  ["Pečení makronek","Stříkej těsto z sáčku do kroužků a sleduj skrz troubu"],
  ["Sušení bylinek","Věš svazky bylin vzhůru nohama pod stropem"],
  ["Nakládání zeleniny","Skládej zeleninu do sklenice a zalévej nálevem"],
  ["Uzení masa","Zavěš maso v udírně a přikládej dřevo do dýmu"],
  ["Vykosťování ryby","Veď nožem podél páteře a odděluj kůstky"]
 ]
},
"Doprava a stroje": {
 1: [
  ["Auto","Drž volant a předstírej řazení rychlostí"],
  ["Autobus","Zatáhni za šňůru zastávky a otevři skládací dveře"],
  ["Vlak","Pohybuj lokty jako píst a houkej píšťalkou"],
  ["Letadlo","Rozpaž ruce jako křídla a nakláněj se do zatáček"],
  ["Loď","Houpej se ze strany na stranu a drž kormidlo"],
  ["Jízdní kolo","Šlapej pedály a zvoň zvonkem"],
  ["Motorka","Přidávej plyn na řídítkách a nakláněj se do zatáčky"],
  ["Traktor","Poskakuj v sedadle a táhni pluh za sebou"],
  ["Vrtulník","Roztoč ruku nad hlavou jako vrtuli a vznes se"],
  ["Raketa","Odpočítávej a vystřel se prudce vzhůru"],
  ["Tank","Dupej pomalu vpřed a otáčej hlavní na věži"],
  ["Ponorka","Klesej pomalu s periskopem nad hlavou"],
  ["Hasičské auto","Houkej sirénou a vytahuj žebřík k oknu"],
  ["Popelářský vůz","Zvedni popelnici hydraulickou paží a vysyp ji"],
  ["Cisterna","Táhni dlouhou nádrž a natáčej se v zatáčkách"],
  ["Náklaďák","Řaď těžké rychlosti a troubi klaksonem"],
  ["Golfový vozík","Pomalu popojížděj po trávníku s golfovými holemi"]
 ],
 2: [
  ["Tramvaj","Kluzej po kolejích a cinkej zvonkem na křižovatce"],
  ["Trolejbus","Jeď tiše a sleduj sběrače jiskřící na drátech"],
  ["Metro","Sjížděj rychle pod zem a drž se madla v tunelu"],
  ["Horkovzdušný balón","Zatáhni za hořák a pomalu stoupej v koši vzhůru"],
  ["Lanovka","Houpej se v kabince vysoko nad údolím"],
  ["Výtah","Zmáčkni tlačítko a stůj nehybně, než se dveře otevřou"],
  ["Eskalátor","Stůj nehybně na schodu, který tě sám veze nahoru"],
  ["Jeřáb","Ovládej páky a zvedej těžké břemeno vysoko"],
  ["Bagr","Nabírej lžící hlínu a vysypávej ji stranou"],
  ["Kombajn","Jeď polem a sklízej obilí širokou lištou"],
  ["Parní lokomotiva","Přikládej uhlí a předveď pravidelné pusinky páry"],
  ["Plachetnice","Napínej plachtu a nakláněj loď proti větru"],
  ["Sanitka","Houkej sirénou a spěchej s nosítky"],
  ["Vor","Vesluj dlouhou tyčí po klidné vodě"],
  ["Segway","Stůj vzpřímeně a nakláněj se vpřed pro pohyb"],
  ["Invalidní vozík","Otáčej koly rukama a pohybuj se po rovině"],
  ["Karavan","Táhni obytný přívěs a otevři sklápěcí stůl uvnitř"],
  ["Sněžný skútr","Přidávej plyn a poskakuj po hrbolatém sněhu"],
  ["Terénní čtyřkolka","Nakláněj se v zatáčkách přes hrbolatý terén"],
  ["Cyklorikša","Šlapej pedály a vez pasažéra v sedačce vzadu"],
  ["Motorový člun","Přidej plyn a nech za sebou stříkat vodní stopu"],
  ["Šlapadlo","Šlapej pedály v sedě a pomalu klouzej po rybníce"]
 ],
 3: [
  ["Vznášedlo","Vznášej se těsně nad vodou na polštáři vzduchu"],
  ["Rogalo","Rozpaž na trojúhelníkové kostře a klouzej ve vzduchu"],
  ["Vzducholoď","Plachtiv pomalu vzduchem jako obří doutník"],
  ["Ledoborec","Prorážej silnou přídí led před sebou"],
  ["Rolba","Uhlazuj sníh na sjezdovce v pravidelných pruzích"],
  ["Rikša","Táhni dvoukolý vozík za sebou pěšky"],
  ["Gondola","Vesluj stoje dlouhým veslem po kanálu a zpívej"],
  ["Trabant","Nastartuj s prskáním a kouř za sebou modrým dýmem"],
  ["Monorail","Jeď tiše po jediné vyvýšené kolejnici"],
  ["Obojživelné vozidlo","Vyjeď z vody rovnou na kola a pokračuj po silnici"],
  ["Vodní skútr","Skákej na vlnách a přidávej plyn na řídítkách"],
  ["Solární auto","Jeď potichu a ukazuj na sluneční panely na střeše"]
 ]
},
"Příroda a svět": {
 1: [
  ["Slunce","Rozpaž paprsky kolem hlavy a hřej se"],
  ["Déšť","Ťukej prsty na hlavu jako kapky a otevři deštník"],
  ["Sníh","Snášej se pomalu s roztaženými prsty jako vločka"],
  ["Vítr","Vlň tělem a rozfoukej si vlasy"],
  ["Bouřka","Zablikej rukama jako blesk a zaduň hromem"],
  ["Duha","Nakresli rukou oblouk barev na obloze"],
  ["Hora","Vypni ruce do špičky nad hlavou jako vrchol"],
  ["Moře","Vlň rukama jako vlny a nasol si rty"],
  ["Řeka","Kliž rukou plynule vpřed jako proud vody"],
  ["Strom","Stůj pevně a rozpaž větve-ruce do stran"],
  ["Květina","Rozevři dlaně jako okvětní lístky a rozkvétej"],
  ["Měsíc","Nakresli srpek rukou a hleď na oblohu"],
  ["Hvězda","Roztáhni ruce a nohy do hvězdice a mrkej"],
  ["Oheň","Vlň rukama vzhůru jako plameny"],
  ["Mrak","Plul pomalu se zaoblenýma rukama nad hlavou"],
  ["Písek","Prosívej si zrnka mezi prsty na pláži"],
  ["Kopec","Předveď menší vyvýšeninu rukou a vyšlapej ji"],
  ["Louka","Rozevři náruč nad barevnými kvítky a lehni si do trávy"],
  ["Les","Stůj rovně mezi ostatními stromy s rukama do korun"]
 ],
 2: [
  ["Sopka","Vytryskni rukama vzhůru jako láva a doutnej"],
  ["Zemětřesení","Rozklepej se a vrávorej, jak se země třese"],
  ["Tornádo","Roztoč se rychle na místě s rukama nahoře"],
  ["Vodopád","Nech ruce padat svisle dolů jako proud vody"],
  ["Poušť","Otírej si čelo a plaz se po horkém písku"],
  ["Ledovec","Stůj strnule a modře jako mohutná kra"],
  ["Jeskyně","Skrč se v úzkém prostoru a ohledávej stěny rukama"],
  ["Ostrov","Stůj samostatně obklopený vodou ze všech stran"],
  ["Mlha","Pohybuj se pomalu s rukama tápajícíma před sebou"],
  ["Krupobití","Poskakuj a kryj si hlavu před padajícími kuličkami"],
  ["Povodeň","Brouzdej se s rukama nad hlavou v stoupající vodě"],
  ["Západ slunce","Pomalu klesej do dřepu s rukama jako paprsky mizícími za obzor"],
  ["Duna","Přesypávej se pomalu jako vlnitý písečný kopec"],
  ["Bažina","Bruď se těžce, jak tě bahno táhne dolů"],
  ["Útes","Stůj vysoko a strmě nad narážejícími vlnami"],
  ["Vichřice","Kloub se prudce a přidržuj si klobouk proti silnému větru"]
 ],
 3: [
  ["Zatmění slunce","Zakryj rukou slunce a nech nastat tmu za bílého dne"],
  ["Polární záře","Vlň rukama barevné pruhy světla po noční obloze"],
  ["Gejzír","Vystřel náhle proud vody a páry vysoko vzhůru"],
  ["Lavina","Řítě se dolů ze svahu s rozevřenýma rukama a rachotem"],
  ["Tsunami","Zvedni ruce vysoko jako obří vlnu valící se na břeh"],
  ["Meteorit","Padej rychle šikmo dolů se zapáleným ohonem"],
  ["Černá díra","Krouž rukama dovnitř, jak vše k sobě vtahuješ"],
  ["Příliv a odliv","Nech vodu-ruce pomalu stoupat a zase klesat"],
  ["Fata morgána","Ukazuj na chvějící se přelud na horizontu, který mizí"],
  ["Kulový blesk","Plav vzduchem jako zářící koule a náhle zmiz"],
  ["Krápníková jeskyně","Ukazuj na visící a rostoucí kamenné špičky kolem"],
  ["Písečná bouře","Zakryj si obličej a bojuj proti hustému vířícímu písku"]
 ]
}
},
en: {
"Animals": {
 1: ["Elephant","Giraffe","Cat","Dog","Snake","Monkey","Cow","Horse","Rabbit","Fish",
     "Bird","Frog","Butterfly","Bee","Lion","Tiger","Bear","Mouse","Hen","Rooster",
     "Pig","Sheep","Duck","Bat","Kangaroo","Penguin","Spider","Turtle","Crocodile","Owl",
     "Hippo","Rhino","Zebra","Swan","Pigeon","Crow","Ladybug","Earthworm","Caterpillar","Goldfish"],
 2: ["Squirrel","Hedgehog","Woodpecker","Stork","Flamingo","Octopus","Shark","Dolphin","Camel","Gorilla",
     "Sloth","Ant","Mosquito","Fly","Snail","Mole","Fox","Wolf","Deer","Eagle",
     "Parrot","Peacock","Donkey","Goat","Beaver","Otter","Walrus","Seal","Crab","Lizard",
     "Cheetah","Lynx","Moose","Reindeer","Llama","Ostrich","Eel","Dragonfly","Cricket (insect)","Grasshopper",
     "Scorpion","Turkey"],
 3: ["Chameleon","Jellyfish","Salamander","Groundhog","Armadillo","Anteater","Platypus","Clam","Firefly","Praying mantis",
     "Stingray","Seahorse","Badger","Wolverine","Meerkat","Emu","Axolotl",
     "Tapir","Capybara","Lemur","Hummingbird","Albatross","Piranha","Iguana","Hyena"]
},
"Professions": {
 1: ["Chef","Firefighter","Police officer","Doctor","Teacher","Dentist","Hairdresser","Painter","Singer","Driver",
     "Photographer","Gardener","Fisherman","Baker","Waiter","Cleaner","Bricklayer","Postman","Shop assistant","Farmer",
     "Soldier","Nurse","Car mechanic","Taxi driver","Actor","Dancer","Ice cream vendor"],
 2: ["Pilot","Chimney sweep","Surgeon","Orchestra conductor","Judge","Priest","Vet","Electrician","Plumber","Carpenter",
     "Tailor","Butcher","Bartender","Miner","Lumberjack","Garbage collector","Astronaut","Diver","Lion tamer","Jockey",
     "TV host","Sculptor","Masseur","Optician","Train conductor","Security guard","Stuntman","Clown","Magician",
     "Lifeguard","Referee","Coach","Receptionist","Flight attendant","Train driver","Crane operator","Excavator operator","Roofer","Watchmaker",
     "Locksmith","Zookeeper","Tour guide","Blacksmith","Model"],
 3: ["Archaeologist","Accountant","Programmer","Lawyer","Psychologist","Weather forecaster","Beekeeper","Art restorer","Notary","Interpreter",
     "Pharmacist","Geologist","Architect","Journalist","Spy","Detective","Gravedigger","Midwife","Croupier","Sommelier",
     "Debt collector","Fortune teller","Shaman","Alchemist","Cartographer","Astronomer","Chemist","Puppeteer","Organist","Pyrotechnician",
     "Piano tuner"]
},
"Activities": {
 1: ["Sleeping","Running","Eating","Drinking","Reading","Writing","Washing hands","Brushing teeth","Combing hair","Making a phone call",
     "Driving a car","Dancing","Singing","Cooking","Ironing","Sweeping","Painting a room","Taking a photo","Fishing","Jumping rope",
     "Riding a bike","Climbing a ladder","Opening a present","Mowing the lawn","Swimming",
     "Taking a shower","Getting dressed","Tying shoelaces","Yawning","Drying dishes","Watering flowers","Drawing","Blowing your nose","Stretching"],
 2: ["Hitchhiking","Packing a suitcase","Hanging laundry","Planting a tree","Milking a cow","Shooting an arrow","Juggling","Chopping wood","Pitching a tent","Playing guitar",
     "Playing piano","Playing drums","Conducting an orchestra","Shaving","Putting on makeup","Knitting","Sewing","Peeling onions","Barbecuing","Mixing a cocktail",
     "Walking the dog","Feeding a baby","Changing a diaper","Washing windows","Wallpapering","Vacuuming","Shopping","Sledding",
     "Painting Easter eggs","Decorating a Christmas tree","Building a snowman","Flying a kite","Blowing bubbles","Doing a puzzle","Playing cards","Changing a light bulb",
     "Changing a tire","Drilling a wall","Hammering a nail","Painting nails","Picking mushrooms","Picking apples"],
 3: ["Meditation","Sleepwalking","Wine tasting","Hypnotizing","Using an ATM","Parallel parking","Snake charming","Tightrope walking","Belly dancing","Tap dancing",
     "Moonwalk","Origami","Spraying graffiti","Sculpting","Shoeing a horse","Dubbing a movie","Preaching","Putting a baby to sleep",
     "Ventriloquism","Palm reading","Crystal ball gazing","Typing on a typewriter","Sending Morse code","Tattooing","Shearing sheep","Braiding hair",
     "Catching butterflies","Starting a campfire"]
},
"Sports": {
 1: ["Football","Ice hockey","Tennis","Basketball","Volleyball","Boxing","Skiing","Ice skating","Golf","Darts",
     "Bowling","Table tennis","Cycling","Competitive swimming",
     "Sprint","Long jump","Rope climbing","Tug of war"],
 2: ["Judo","Fencing","Archery","Rowing","Rock climbing","Figure skating","Pole vault","High jump","Javelin throw","Hammer throw",
     "Weightlifting","Gymnastics","Yoga","Surfing","Sailing","Baseball","Cricket","Rugby","Curling","Biathlon",
     "Water polo","Badminton","Squash","Springboard diving","Snowboarding","Skateboarding",
     "Floorball","Handball","Marathon","Roller skating","Sport shooting","Motocross","Formula racing","Aerobics","Ballet","Race walking",
     "Hurdles","Shot put","Discus throw"],
 3: ["Sumo","Pétanque","Canoeing","Chess","Parkour","Triple jump","Synchronized swimming","Ski jumping","Speed skating","Field hockey",
     "Lacrosse","Bungee jumping","Paragliding","Orienteering","Rhythmic gymnastics","Trampolining",
     "Kitesurfing","Water skiing","Horse dressage","Snorkeling","Greco-Roman wrestling","Taekwondo","Bobsleigh","Skeleton (sled)"]
},
"Objects": {
 1: ["Umbrella","Toothbrush","Scissors","Hammer","Phone","Glasses","Book","Key","Watch","Chair",
     "Spoon","Knife","Fork","Pot","Pillow","Mirror","Ball","Balloon","Candle","Guitar",
     "Pencil","Comb","Towel","Soap","Wallet","Lamp","Bed","Broom","Gloves","Hat","Scarf"],
 2: ["Vacuum cleaner","Microwave","Hair dryer","Screwdriver","Saw","Axe","Shovel","Rake","Watering can","Binoculars",
     "Microscope","Compass","Camera","Headphones","Piano","Drum","Trumpet","Violin","Tent","Sleeping bag",
     "Flashlight","Lighter","Corkscrew","Can opener","Grater","Rolling pin","Whisk","Thermometer","Syringe","Crutches",
     "Microphone","Whistle","Bell","Flute","Saxophone","Wheelbarrow","Scythe","Pitchfork","Slingshot","Sword",
     "Shield","Helmet","Kick scooter","Pliers","Tweezers","Magnifying glass"],
 3: ["Periscope","Pendulum","Metronome","Traffic light","Lighthouse","Catapult","Parachute","Boomerang","Harp","Bagpipes",
     "Accordion","Spinning wheel","Hourglass","X-ray machine","Metal detector","Lightning rod","Safe","Mousetrap",
     "Gramophone","Globe","Kaleidoscope","Fire extinguisher","Defibrillator","Stethoscope","Chopsticks","Rocking chair"]
},
"Emotions & states": {
 1: ["Joy","Sadness","Anger","Fear","Tiredness","Boredom","Surprise","Crying","Laughing","Hunger",
     "Thirst","Freezing","Feeling hot","Toothache","Being in love",
     "Sleepiness","Being tickled","Itching","Headache","Stomachache","Runny nose","Coughing","Fever"],
 2: ["Jealousy","Shame","Nervousness","Disappointment","Pride","Disgust","Curiosity","Impatience","Relief","Exhaustion",
     "Excitement","Stage fright","Dizziness","Hiccups","Sneezing","Allergy","Insomnia","Seasickness",
     "Drunkenness","Confusion","Stress","Panic","Nausea","Leg cramp"],
 3: ["Nostalgia","Envy","Embarrassment","Melancholy","Euphoria","Paranoia","Déjà vu","Claustrophobia","Guilt","Compassion",
     "Gratitude","Deep in thought","Absent-mindedness","Suspicion",
     "Sarcasm","Indecision","Despair","Optimism","Pessimism","Indifference","Loneliness","Being moved to tears","Amnesia"]
},
"Movies & fairy tales": {
 1: ["Cinderella","Little Red Riding Hood","Snow White","Devil","Angel","Dragon","Princess","King","Knight","Witch",
     "Ghost","Vampire","Pirate","Superman","Spiderman","Batman","Santa Claus",
     "Giant","Fairy","Bandit","Mummy","Skeleton","Zombie"],
 2: ["Harry Potter","Shrek","Tarzan","Robin Hood","Peter Pan","Pinocchio","The Snow Queen","Goldilocks","Zorro","James Bond",
     "King Kong","Godzilla","Yoda","Darth Vader","Minion","Elsa (Frozen)","Mermaid","Aladdin","Hercules","Sherlock Holmes",
     "Werewolf","Puss in Boots","Baron Munchausen","Asterix","Obelix","Popeye","Winnie the Pooh","Mickey Mouse",
     "Donald Duck","Tom and Jerry","SpongeBob","Scooby-Doo"],
 3: ["Golem","Frankenstein","Dracula","Gandalf","Gollum","Hobbit","Terminator","Rocky","Indiana Jones","Jack Sparrow",
     "Forrest Gump","Mary Poppins","Edward Scissorhands","Wizard of Oz","E.T.","Neo (Matrix)","Willy Wonka","Hulk",
     "Captain Hook","Don Quixote","The Three Musketeers","Robinson Crusoe","Gulliver","Charlie Chaplin","Mr. Bean","Rambo","King Arthur"]
},
"Food & cooking": {
 1: ["Spaghetti","Ice cream","Banana","Apple","Lemon","Popcorn","Pizza","Soup","Lollipop","Chewing gum",
     "Bread","French fries","Cake","Chocolate","Candy","Honey","Milk","Tea","Yogurt","Donut"],
 2: ["Pancakes","Hamburger","Sushi","Roast chicken","Soft-boiled egg","Corn on the cob","Watermelon","Coconut","Pineapple","Chili pepper",
     "Garlic","Onion","Whipped cream","Fondue","Hot dog","Milkshake","Taco","Kebab",
     "Grilled cheese sandwich","Schnitzel","Spinach","Pickle","Beer","Burrito","Pretzel"],
 3: ["Caviar","Oysters","Champagne","Espresso","Croissant","Steak tartare","Snails","Cotton candy","Ribs","Tortilla",
     "Hot wings","Roasting marshmallows",
     "Lobster","Artichoke","Flambéing","Making jam","Pomegranate"]
},
"Vehicles & machines": {
 1: ["Car","Bus","Train","Airplane","Ship","Bicycle","Motorcycle","Tractor","Helicopter","Rocket",
     "Tank","Submarine"],
 2: ["Tram","Trolleybus","Subway","Hot air balloon","Cable car","Elevator","Escalator","Crane","Excavator","Combine harvester",
     "Steam locomotive","Sailboat","Ambulance","Raft","Segway","Wheelchair"],
 3: ["Hovercraft","Hang glider","Airship","Icebreaker","Snow groomer","Rickshaw","Gondola","Golf cart"]
},
"Nature & world": {
 1: ["Sun","Rain","Snow","Wind","Thunderstorm","Rainbow","Mountain","Sea","River","Tree",
     "Flower","Moon","Star","Fire"],
 2: ["Volcano","Earthquake","Tornado","Waterfall","Desert","Glacier","Cave","Island","Fog","Hailstorm",
     "Flood","Sunset"],
 3: ["Solar eclipse","Northern lights","Geyser","Avalanche","Tsunami","Meteorite","Black hole","Tide","Mirage"]
}
}
};
